### ISSUE TITLE
callback never gets called on readyState interactive

### ISSUE THREAD

**Issue by HaNdTriX** [nicbell/liteready#1]
> **interactive**
> The document has finished loading and the document has been parsed but sub-resources such as images, stylesheets and frames are still loading. The state indicates that the DOMContentLoaded event has been fired.

```
window.addEventListener( "load", callback, false );
```

should solve the issue :)

**Comment by nicbell** [comment]
"The state indicates that the DOMContentLoaded event has been fired." We are attaching to `DOMContentLoaded` so be definition it should fire.

Is there a specific browser causing this issue?

**Comment by HaNdTriX** [comment]
yepp almost all browsers.

Lets say the current `readyState` is `interactive`:

```
document.readyState === 'complete'
  => false;

document.addEventListener('DOMContentLoaded', callback)
  => has already been fired 

document.attachEvent
  => undefined
```

The state `interactive` indicates that the DOMContentLoaded event has been fired. So attaching to DOMContentLoaded will do nothing.

https://developer.mozilla.org/en/docs/Web/API/Document/readyState

**Comment by HaNdTriX** [comment]
Thanks!

**Comment by nicbell** [comment]
No problem, thanks for finding the bug.
